digital_resume/urls.py
from django.contrib import admin
from django.urls import path , include, re_path
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve
# from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls', namespace = "main")),
    re_path(r'^media/(?P<path>.*)$', serve,
        {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve,
        {'document_root': settings.STATIC_ROOT}),
]

main/urls.py
from django.urls import path
from . import views


app_name = "main"

urlpatterns = [
	path('', views.IndexView.as_view(), name="home"),
	path('contact/', views.ContactView.as_view(), name="contact"),
	path('portfolio/', views.PortfolioView.as_view(), name="portfolios"),
	path('portfolio/<slug:slug>', views.PortfolioDetailView.as_view(), name="portfolio"),
	path('blog/', views.BlogView.as_view(), name="blogs"),
	path('blog/<slug:slug>', views.BlogDetailView.as_view(), name="blog"),
	]

main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from ckeditor.fields import RichTextField


class Skill(models.Model):
    class Meta:
        verbose_name_plural = "Skills"
        verbose_name = 'Skill'

    
    name = models.CharField(max_length=150, blank=True, null=True)
    score = models.IntegerField(default=80,blank=True, null= True)
    image = models.FileField(blank=True, null= True, upload_to= "skills")
    is_key_skill = models.BooleanField(default= False)

    def __str__(self):
        return self.name
    

class UserProfile(models.Model):

    class Meta:
        verbose_name_plural = 'User Profiles'
        verbose_name = 'User Profile'
    
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    username = models.ImageField(blank=True, null=True, upload_to="avatar")
    title = models.CharField(max_length=200, blank=True, null=True)
    bio = models.TextField(blank=True, null=True)
    skills = models.ManyToManyField(Skill, blank=True)
    cv = models.FileField(blank=True, null=True, upload_to="cv")

    def __str__(self):
        return f'{self.user.first_name} {self.user.last_name}'


class ContactProfile(models.Model):
    
    class Meta:
        verbose_name_plural = 'Contact Profiles'
        verbose_name = 'Contact Profile'
        ordering = ["timestamp"]
    timestamp = models.DateTimeField(auto_now_add=True)
    name = models.CharField(verbose_name="Name",max_length=100)
    email = models.EmailField(verbose_name="Email")
    message = models.TextField(verbose_name="Message")

    def __str__(self):
        return f'{self.name}'
    

class Testimonial(models.Model):

    class Meta:
        verbose_name_plural = 'Testimonials'
        verbose_name = 'Testimonial'
        ordering = ["name"]

    thumbnail = models.ImageField(blank=True, null=True, upload_to="testimonials")
    name = models.CharField(max_length=200, blank=True, null=True)
    role = models.CharField(max_length=200, blank=True, null=True)
    quote = models.CharField(max_length=500, blank=True, null=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name
    

class Media(models.Model):

    class Meta:
        verbose_name_plural = 'Media Files'
        verbose_name = 'Media'
        ordering = ["name"]
	
    image = models.ImageField(blank=True, null=True, upload_to="media")
    url = models.URLField(blank=True, null=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    is_image = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        if self.url:
            self.is_image = False
        super(Media, self).save(*args, **kwargs)
    def __str__(self):
        return self.name
    

class Portfolio(models.Model):

    class Meta:
        verbose_name_plural = 'Portfolio Profiles'
        verbose_name = 'Portfolio'
        ordering = ["name"]
    date = models.DateTimeField(blank=True, null=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    description = models.CharField(max_length=500, blank=True, null=True)
    body = RichTextField(blank=True, null=True)
    image = models.ImageField(blank=True, null=True, upload_to="portfolio")
    slug = models.SlugField(null=True, blank=True)
    is_active = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)
        super(Portfolio, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f"/portfolio/{self.slug}"
    

class Blog(models.Model):

    class Meta:
        verbose_name_plural = 'Blog Profiles'
        verbose_name = 'Blog'
        ordering = ["timestamp"]

    timestamp = models.DateTimeField(auto_now_add=True)
    author = models.CharField(max_length=200, blank=True, null=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    description = models.CharField(max_length=500, blank=True, null=True)
    body = RichTextField(blank=True, null=True)
    slug = models.SlugField(null=True, blank=True)
    image = models.ImageField(blank=True, null=True, upload_to="blog")
    is_active = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)
        super(Blog, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f"/blog/{self.slug}"
    


class Certificate(models.Model):

    class Meta:
        verbose_name_plural = 'Certificates'
        verbose_name = 'Certificate'

    date = models.DateTimeField(blank=True, null=True)
    name = models.CharField(max_length=50, blank=True, null=True)
    title = models.CharField(max_length=200, blank=True, null=True)
    description = models.CharField(max_length=500, blank=True, null=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name
    
class Experience(models.Model):

    class Meta:
        verbose_name_plural = 'Work Expreience'
        verbose_name = 'Experience'

    start_date = models.DateField(blank=False)
    end_date = models.DateField(blank=True,null = True)
    company_name = models.CharField(max_length=100, blank=True, null=True)
    job_title = models.CharField(max_length=200, blank=True, null=True)
    description = models.CharField(max_length=1000, blank=True, null=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.company_name

main/forms.py
from django import forms
from .models import ContactProfile


class ContactForm(forms.ModelForm):

	name = forms.CharField(max_length=100, required=True,
		widget=forms.TextInput(attrs={
			'placeholder': '*Full name..',
			'class': 'form-control'
			}))
	email = forms.EmailField(max_length=254, required=True, 
		widget=forms.TextInput(attrs={
			'placeholder': '*Email..',
			'class': 'form-control'
			}))
	message = forms.CharField(max_length=1000, required=True, 
		widget=forms.Textarea(attrs={
			'placeholder': '*Message..',
			'class': 'form-control',
			'rows': 6,
			}))


	class Meta:
		model = ContactProfile
		fields = ('name', 'email', 'message',)

main/views.py
from django.shortcuts import render
from django.contrib import messages
from .models import (
		UserProfile,
		Blog,
		Portfolio,
		Testimonial,
		Certificate,
		Experience
	)

from django.views import generic


from . forms import ContactForm


class IndexView(generic.TemplateView):
	template_name = "main/index.html"

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		
		testimonials = Testimonial.objects.filter(is_active=True)
		certificates = Certificate.objects.filter(is_active=True)
		blogs = Blog.objects.filter(is_active=True)
		portfolio = Portfolio.objects.filter(is_active=True)
		experience = Experience.objects.filter(is_active=True)

		context["testimonials"] = testimonials
		context["certificates"] = certificates
		context["blogs"] = blogs
		context["portfolio"] = portfolio
		context["experience"] = experience
		return context


class ContactView(generic.FormView):
	template_name = "main/contact.html"
	form_class = ContactForm
	success_url = "/"
	
	def form_valid(self, form1):
		form1.save()
		messages.success(self.request, 'Thank you. I will be in touch soon.')
		return super().form_valid(form1)


class PortfolioView(generic.ListView):
	model = Portfolio
	template_name = "main/portfolio.html"
	paginate_by = 10

	def get_queryset(self):
		return super().get_queryset().filter(is_active=True)


class PortfolioDetailView(generic.DetailView):
	model = Portfolio
	template_name = "main/portfolio-detail.html"

class BlogView(generic.ListView):
	model = Blog
	template_name = "main/blog.html"
	paginate_by = 10
	
	def get_queryset(self):
		return super().get_queryset().filter(is_active=True)


class BlogDetailView(generic.DetailView):
	model = Blog
	template_name = "main/blog-detail.html"

main/templates/main/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}{%endblock %}</title>
    <meta name="author" content="Did Coding Limited & James Granger Design">
    <link rel="canonical" href="{{request.path}}"/>
    <link rel="home" href="{% url 'main:home' %}"/>
    <meta name="description" content="{% block description %}{% endblock %}">
    <meta name="keywords" content="{% block keywords %}{% endblock %}">

    <!-- <link rel="shortcut icon" type="image/x-icon" href="{% static 'images/icon.jpg' %}">
    <link rel="apple-touch-icon" type="image/jpg" href="{% static 'images/icon.jpg' %}"> -->

    <!-- ================================
    Start CSS
    ================================= -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://unpkg.com/swiper@7.0.5/swiper-bundle.min.css">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    {% block extend_header%}{%endblock%}
    <!-- ================================
    End CSS
    ================================= -->

  </head>
  <body>
    {% include 'partials/messages.html' %}
    {% include 'partials/nav.html' %}

    {% block content %}
    {% endblock %}

    {% include 'partials/footer.html' %}

    <!-- ================================
    Start Scripts
    ================================= -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="https://unpkg.com/swiper@7.0.5/swiper-bundle.min.js"></script>
    <script src="{% static 'js/script.js' %}"></script>
    {% block extend_footer %}{%endblock%}
    <!-- ================================
    End Scripts
    ================================= -->
  </body>
</html>

main/templates/main/blog-detail.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Did Coding - Blog Detail</title>
    <meta name="author" content="Did Coding Limited & James Granger Design">
    <link rel="canonical" href=""/>
    <link rel="home" href=""/>
    <meta name="description" content="">
    <meta name="keywords" content="">

    <!-- ================================
    Start CSS
    ================================= -->
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://unpkg.com/swiper@7.0.5/swiper-bundle.min.css">
    <link href="css/style.css" rel="stylesheet">
    <!-- ================================
    End CSS
    ================================= -->

  </head>
  <body>

    <!-- ================================
    Start Navigation Bar
    ================================= -->
    <header>
      <div class="headerCol">
        <div class="container-fluid">
          <div class="row align-items-center">
            <div class="col-auto">
              <div class="logoCol"><a href="index.html"><img src="images/logo.png" alt="..."></a></div>
            </div>
            <div class="col">
              <div class="d-md-none">
                <button class="navToggle">
                  <span class="navToggle__text">Toggle Menu</span>
                </button>
              </div>
              <div class="navCollapseCol">
                <div class="navCol">
                  <ul>
                    <li><a href="index.html">Home</a></li>
                    <li><a href="portfolio.html">Portfolio</a></li>
                    <li><a href="blog.html">Blog</a></li>
                    <li><a href="contact.html">Contact</a></li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </header>
    <!-- ================================
    End Navigation Bar
    ================================= -->

    <!-- ================================
    Start Content
    ================================= -->
    <section>
      <div class="innerPageBannerCol">
        <div class="container">
          <div class="row g-4 g-md-3  align-items-center">
            <div class="col-md-6">
              <div class="bannerContent">
                <h1 class="xlTitle pb-md-3">Blog title</h1>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-auto">
              <div class="authorCol">
                <h4 class="smTitle pb-3">Bobby Stearman</h4>
              </div>
            </div>
            <div class="col-md">
              <h4 class="smTitle pb-3">12-10-2021</h4>
            </div>
          </div>
        </div>
      </div>
    </section>

    <section>
      <div class="sectionSpaceSm">
        <div class="container">
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
          Aenean congue imperdiet lorem ut posuere. Maecenas nec accumsan 
          risus, quis luctus libero. Morbi a nulla ac felis scelerisque 
          feugiat quis vitae turpis. Vivamus nec augue vel enim scelerisque 
          cursus. Curabitur efficitur ipsum quis turpis bibendum egestas. 
          Nunc ac euismod dolor. Vestibulum nec ipsum fermentum, semper 
          quam eu, porttitor elit. Maecenas efficitur ex eget augue euismod 
          semper. Curabitur pharetra tortor vel orci volutpat semper. 
          Donec feugiat mauris ante. In hac habitasse platea dictumst.
          </p>
        </div>
      </div>
    </section>
    <!-- ================================
    End Content
    ================================= -->
    
    <!-- ================================
    Start Footer
    ================================= -->
    <footer>
      <div class="footerCol">
        <div class="container">
          <ul class="socialCol">
            <li><a href="javascript:void(0)"><img src="images/fb.svg" alt="..."></a></li>
            <li><a href="javascript:void(0)"><img src="images/insta.svg" alt="..."></a></li>
            <li><a href="javascript:void(0)"><img src="images/twitter.svg" alt="..."></a></li>
            <li><a href="javascript:void(0)"><img src="images/linkedin.svg" alt="..."></a></li>
          </ul>
          <div class="copyrightCol">
            <p>Copyright ©2021 All rights reserved. Designed by <a href="https://jamesgrangerdesign.co.uk/" target="_blank">James Granger Design</a></p>
          </div>
        </div>
      </div>
    </footer>
    <!-- ================================
    End Footer
    ================================= -->

    <!-- ================================
    Start Scripts
    ================================= -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="js/bootstrap.bundle.min.js"></script>
    <script src="https://unpkg.com/swiper@7.0.5/swiper-bundle.min.js"></script>
    <script src="js/script.js"></script>
    <!-- ================================
    End Scripts
    ================================= -->
  </body>
</html>

main/templates/main/index.html
{% extends 'main/base.html' %}
{% load static %}

<!-- ================================
Start SEO blocks
================================= -->
{% block title %}{% endblock %}
{% block decription %}{% endblock %}
{% block keywords %}{% endblock %}
<!-- ================================
END SEO blocks
================================= -->

<!-- ================================
Start CSS blocks
================================= -->
{% block extend_header %}{% endblock %}
<!-- ================================
END CSS blocks
================================= -->

<!-- ================================
Start script blocks
================================= -->
{% block extend_footer %}{% endblock %}
<!-- ================================
END script blocks
================================= -->

<!-- ================================
Start Content
================================= -->
{% block content %}
<section>
  <div class="bannerSection">
    <div class="container">
      <div class="row g-4 g-md-3  align-items-center">
        <!-- <div class="col-md-auto order-md-last">
          <div class="bannerUserImg">
            <img src="{{me.userprofile.username.url}}" alt="{{me.first_name|title}} {{me.last_name|title}} avatar">
          </div>
        </div> -->
        <div class="col-md">
          <div class="bannerContent" style="text-justify: inter-word;">
            <h1 class="smTitle pb-3" >
              I view my career as more than just a job, it's a platform for personal development and growth. With every step,
              I am not only building a career, but also nurturing the best version of myself. 
            
            </h1>
            <!-- Hi, my name is Suraj Acharya {{me.first_name|title}}, <br> a {{me.userprofile.title}} </br> -->
            <p> 
            <!-- Hi, my name is Suraj Acharya. {{me.userprofile.bio}} -->
            Hi, my name is Suraj Acharya. Three years of practical experience as a SQL and BI developer having analyzed complex datasets, identified trends, and provided useful insights. 
            Strong in SQL query optimization and data-driven decision-making. Additionally, my expertise extends to designing predictive models using statistical modeling and machine learning algorithms, coupled with a strong background in programming, data manipulation, and data visualization.
             As a highly motivated and analytically minded data enthusiast, my goal is to apply my combined knowledge of Data Engineering and Data Scientist to help the organization succeed in an increasingly data-centric world by contributing to data-driven decision-making processes, encouraging creativity, and empowering them to innovate.
            </p>
             <div class="bannerBtnCol">
              <div class="row">
                <!-- <div class="col-auto">
                  <a download href="{{me.userprofile.cv.url}}" class="btn btnPrimary">Download Resume</a>
                </div> -->
                <div class="col-auto">
                  <a href="{% url 'main:contact' %}" class="btn btnOutline">Contact</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section> 

<section>
  <div class="sectionSpace pt-0">
    <div class="container">
      <div class="row">
        <div class="col-md-auto">
          <div class="keySkillCol">
            <h4 class="smTitle pb-3">Key Skills</h4>
            {% for sk in me.userprofile.skills.all %}
            {% if sk.is_key_skill %}
            <div class="keySkillCard">
              {% if sk.image %} 
              <div class="ksIconCol">
                <img src="{{sk.image.url}}" alt="...">
              </div>
              {% endif %}
              <span class="ksText">{{sk.name}}</span>
            </div>
            {% endif %}
            {% endfor %}
          </div>
        </div> 
        <div class="col-md"> 
          <h4 class="smTitle pb-3">Technical Skills</h4>
          
          <div class="progressCol">
            <div class="progressCard">
              {% for sk in me.userprofile.skills.all %}
              {% if not sk.is_key_skill %}
              <div class="progressCol">
                <span class="progressLbl">{{sk.name}}</span>
                <div class="row g-2 align-items-center">
                  <div class="col">
                    <div class="progress progressStyle">
                      <div class="progress-bar" role="progressbar" style="width: {{sk.score}}%" aria-valuenow="{{sk.score}}" aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                  </div>
                  <!-- <div class="col-auto">
                    <span class="pLbl">{{sk.score}}%</span>
                  </div> -->
                </div>
              </div>
              
              {% endif %}
              {% endfor %}
              
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>




<section>
  <div class="sectionSpace lightBg">
    <div class="container">
      <div class="portfolioCol">
        <div class="row pb-3">
          <div class="col">
            <h4 class="smText regular">Work Experience</h4>
          </div>
        </div>
        <div>
            {% for c in experience %}
            {% if c.is_active %}
            <div class="swiper-slide">
              <div class="cardStyle1">
                <h4 class="mdTitle cs1Title">
                  {{c.job_title}}
                </h4>
                <ul class="cardOptionCol">
                  <li>{{c.start_date}}</li> 
                  <li>{{c.end_date}}</li> 
                  <li><strong>{{c.company_name|title}}</strong></li>
                </ul>
                <h3 class="smText">Job Description</h3>
                <p>{{c.description}}</p>
              </div>
            </div>
            
            {% endif %}                 
            {% endfor %}
          </div>          
        </div>
      </div>
    </div>
</section>


<!-- <section>
  <div class="sectionSpaceSm lightBg">
    <div class="container">
      <div class="row pb-3">
        <div class="col">
          <h4 class="smText regular">Work Experience</h4>
        </div>

      </div>
      <div class="sliderOuter">
        <div class="swiper certificatesSlider">
          <div class="swiper-wrapper">
            {% for c in certificates %}
            {% if c.is_active %}
            <div class="swiper-slide">
              <div class="cardStyle1">
                <h4 class="mdTitle cs1Title">
                  <a href="javascript:void(0)">{{c.title}}</a>
                </h4>
                <ul class="cardOptionCol">
                  <li>{{c.date.date}}</li> 
                  <li>{{c.name|title}}</li>
                </ul>
                <p>{{c.description}}</p>
              </div>
            </div>
            {% endif %}
            {% endfor %}
            
          </div>
        </div>            
        <div class="cert-swiper-button-next swiper-button-next swiperBtnStyle"></div>
        <div class="cert-swiper-button-prev swiper-button-prev swiperBtnStyle"></div>
        <div class="swiper-pagination swiperPaginationStyle posInitial"></div>
      </div>
    </div>
  </div>
</section> -->



<!-- bottom section -->
<!-- 
<section>
  <div class="sectionSpace">
    <div class="container">
      <div class="portfolioCol">
        <div class="row pb-3">
          <div class="col">
            <h4 class="smText regular">Featured Work</h4>
          </div>
          <div class="col-auto">
            <a href="{% url 'main:portfolios' %}" class="simpleLink">View all</a>
          </div>
        </div>
        {% for p in portfolio %}
        {% if p.is_active %}
        <div class="portfolioCard">
          <div class="row g-4 align-items-center">
            <div class="col-md-auto">
              <div class="portfolioImgCol">
                <a href="{% url 'main:portfolio' slug=p.slug %}"><img src="{{p.image.url}}" alt="..."></a>
              </div>
            </div>
            <div class="col-md">
              <div class="portfolioContentCol">
                <h4 class="lgTitle"><a href="{% url 'main:portfolio' slug=p.slug %}">{{p.name}}</a></h4>
                <ul class="portfolioOption">
                  <li><span class="dateLbl">{{p.date.year}}</span></li>
                </ul>
                <p>{{p.description}}</p>
              </div>
            </div>
          </div>
        </div>
        {% endif %}
        {% endfor %}
        
      </div>
      <div class="testimonialCol">
        <h4 class="smText regular d-block">Testimonials</h4>
        <div class="testimonialSlider">
          <div class="swiper testimonialSwiper">
            <div class="swiper-wrapper">
              {% for t in testimonials %}
              {% if t.is_active %}
              <div class="swiper-slide">
                <div class="testimonialCard">
                  <div class="row align-items-center">
                    <div class="col-sm-auto">
                      <div class="tImgCol">
                        <img src="{{t.thumbnail.url}}" alt="...">
                      </div>
                    </div>
                    <div class="col-sm">
                      <div class="tContentCol">
                        <h4 class="xsTitle bold">{{t.name}} - {{t.role}}</h4>
                        <p>{{t.quote}}</p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              {% endif %}
              {% endfor %}

            </div>
            <div class="test-swiper-button-next swiper-button-next swiperBtnStyle"></div>
            <div class="test-swiper-button-prev swiper-button-prev swiperBtnStyle"></div>
          </div>


        </div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="sectionSpaceSm lightBg">
    <div class="container">
      <div class="row pb-3">
        <div class="col">
          <h4 class="smText regular">Recent posts</h4>
        </div>
        <div class="col-auto">
          <a href="{% url 'main:blogs' %}" class="simpleLink">View all</a>
        </div>
      </div>
      <div class="row g-3">
      {% for b in blogs %}
      {% if b.is_active %}
        <div class="col-lg-6">
          <div class="cardStyle1">
            <h4 class="mdTitle cs1Title"><a href="{% url 'main:blog' slug=b.slug %}">{{b.name}}</a></h4>
            <ul class="cardOptionCol">
              <li>{{b.timestamp.date}}</li>
              <li>{{b.author}}</li>
            </ul>
            <p>{{b.description}}</p>
          </div>
        </div>
        {% endif %}
        {% endfor %}

      </div>
    </div>
  </div>
</section> -->
{% endblock %}
<!-- ================================
End Content
================================= -->

main/templates/main/portfolio.html
{% extends 'main/base.html' %}
{% load static %}

<!-- ================================
Start SEO blocks
================================= -->
{% block title %}portfolio test{% endblock %}
{% block decription %}{% endblock %}
{% block keywords %}{% endblock %}
<!-- ================================
END SEO blocks
================================= -->

<!-- ================================
Start CSS blocks
================================= -->
{% block extend_header %}{% endblock %}
<!-- ================================
END CSS blocks
================================= -->

<!-- ================================
Start script blocks
================================= -->
{% block extend_footer %}{% endblock %}
<!-- ================================
END script blocks
================================= -->

<!-- ================================
Start Content
================================= -->
{% block content %}
<section>
  <div class="innerPageBannerCol">
    <div class="container">
      <div class="row g-4 g-md-3  align-items-center">
        <div class="col-md-12">
          <div class="bannerContent">
            <h1 class="xlTitle pb-md-3">See my recent projects below</h1>
          </div>          
        </div>       
      </div>
      
  </div>

  <div>

    <div class="lightBg">
      <div class = "container">
        <ul>
          <li class="smText pb-md-3">Prediction of Heart Disease - <a href="https://github.com/surajacharya62/HeartDiseasePrediction/blob/main/HeartDiseasePrediction.ipynb" class="btn btnOutline"> View</a> </li> 
        </ul>
        <ul>
          <li class="smText pb-md-3">Prediction of age on EEG Signals data using Transfer Learning - <a href="https://github.com/surajacharya62/Predicting-Age-using-Transfer-Learning-on-EEG-brain-signal/blob/main/Main%20Final_project.ipynb" class="btn btnOutline"> View</a> </li> 
        </ul>
        <ul>
          <li class="smText pb-md-3">Employee performance analysis - <a href="https://github.com/surajacharya62/EmployeePerformanceAnalysis/blob/main/Employee_Performance_Analysis_IABAC.ipynb" class="btn btnOutline"> View</a> </li> 
        </ul>
      </div>
  </div>
  </div>
  </div>
</section>

<!-- <section>
  <div class="lightBg">
      <div class = "container">
        <ul>
          <li class="smText pb-md-3">Prediction of Heart Disease - <a href="https://github.com/surajacharya62/HeartDiseasePrediction/blob/main/HeartDiseasePrediction.ipynb" class="btn btnOutline"> View</a> </li> 
        </ul>
        <ul>
          <li class="smText pb-md-3">Prediction of age on EEG Signals data using Transfer Learning - <a href="https://github.com/surajacharya62/HeartDiseasePrediction/blob/main/HeartDiseasePrediction.ipynb" class="btn btnOutline"> View</a> </li> 
        </ul>
        <ul>
          <li class="smText pb-md-3">Employee performance analysis - <a href="https://github.com/surajacharya62/HeartDiseasePrediction/blob/main/HeartDiseasePrediction.ipynb" class="btn btnOutline"> View</a> </li> 
        </ul>
      </div>
  </div>
</section> -->
<!-- 
<section>
  <div class="lightBg">
    <div class="container">
      <div class="portfolioContentMain">
        <div class="row g-3 g-md-4 g-lg-5 portfolioRow">
          {% for obj in object_list %}
          <div class="col-md-6 pColMain">
            <div class="pCol">
              <a href="{% url 'main:portfolio' slug=obj.slug %}" > {{ obj.name}}
              <img src="{{obj.image.url}}" alt=".khkjh.." class="pImg">
              </a>
            </div>
          </div>
          {% endfor %}
          
        </div>
      </div>
    </div>
  </div>
</section> -->
<!-- ================================
End Content
================================= -->
{% endblock%}    